import '../styles/globals.scss';
import Header from '../components/Header';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Sarah Bowes Design</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
