import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sarah Bowes Design</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className={styles.main}>
        <h1>I am the home page</h1>
      </main>
    </>
  );
}
